[package]
name = "bottomless-pit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = {version = "1.12.3", features = ["derive"]}
env_logger = "0.10.0"
log = "0.4.17"
pollster = "0.2.5"
wgpu = "0.15"
winit = "0.28.2"
cgmath = "0.18.0"
crc32fast = "1.3.2"
glyph_brush = "0.7"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
