[package]
name = "text-render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glyph_brush = "0.7.5"
wgpu = "0.14.2"

[dependencies.bytemuck]
version = "1.12.3"
features = ["derive"]